(ns neovim-cljs.tcp-ip+api
  (:require [net]
            [goog.string :as gstr]
            [goog.object :as gobj]
            [shelljs]
            [msgpack-lite]
            [cljs.nodejs :as nodejs]))




(def tmp
  ["connecting"
   "_hadError"
   "_handle"
   "_parent"
   "_host"
   "_readableState"
   "readable"
   "domain"
   "_events"
   "_eventsCount"
   "_maxListeners"
   "_writableState"
   "writable"
   "allowHalfOpen"
   "_bytesDispatched"
   "_sockname"
   "_pendingData"
   "_pendingEncoding"
   "server"
   "_server"
   "_unrefTimer"
   "read"
   "listen"
   "setTimeout"
   "_onTimeout"
   "setNoDelay"
   "setKeepAlive"
   "address"
   "_read"
   "end"
   "destroySoon"
   "_destroy"
   "_getpeername"
   "bytesRead"
   "remoteAddress"
   "remoteFamily"
   "remotePort"
   "_getsockname"
   "localAddress"
   "localPort"
   "write"
   "_writeGeneric"
   "_writev"
   "_write"
   "bytesWritten"
   "connect"
   "ref"
   "unref"
   "cork"
   "uncork"
   "setDefaultEncoding"
   "destroy"
   "_undestroy"
   "push"
   "unshift"
   "isPaused"
   "setEncoding"
   "pipe"
   "unpipe"
   "on"
   "addListener"
   "resume"
   "pause"
   "wrap"
   "setMaxListeners"
   "getMaxListeners"
   "emit"
   "prependListener"
   "once"
   "prependOnceListener"
   "removeListener"
   "removeAllListeners"
   "listeners"
   "listenerCount"
   "eventNames"])
